"""empty message

Revision ID: 653f3ab3d7e9
Revises: 7b3305ecc09d
Create Date: 2024-02-20 17:42:00.359454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653f3ab3d7e9'
down_revision: Union[str, None] = '7b3305ecc09d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
